packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@babel/parser": ^7.29.2
  "@babel/traverse": ^7.29.0
  "@babel/types": ^7.29.0
  "@types/babel__traverse": ^7.28.0
  "@types/node": ^24
  "@vitest/coverage-v8": ^4.1.0
  esbuild: ^0.27.0
  puppeteer: ^24.40.0
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitepress: ^1.6.4
  vitepress-carbon: ^1.5.0
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
